package ru.nnsu.pacman.client;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CreateGameForm extends javax.swing.JPanel {
    private final ClientNavigator navigator;
    private final GameClient gameClient;
    private final CreateGameViewModel viewModel;

    CreateGameForm(ClientNavigator navigator, GameClient gameClient, CreateGameViewModel viewModel) {
        initComponents();
        this.navigator = navigator;
        this.gameClient = gameClient;
        this.viewModel = viewModel;

        this.MapComboBox.setModel(viewModel.getMapModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateGameButton = new javax.swing.JButton();
        MapComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        JoinGame = new javax.swing.JButton();

        CreateGameButton.setText("Создать игру");
        CreateGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGameButtonActionPerformed(evt);
            }
        });

        MapComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lost Temple", "Dish hample", "Cave riddings" }));

        jLabel1.setText("Выберите карту");

        JoinGame.setText("Подключиться к игре");
        JoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MapComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CreateGameButton)
                    .addComponent(JoinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MapComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateGameButton)
                .addGap(18, 18, 18)
                .addComponent(JoinGame)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGameButtonActionPerformed
        String current = MapComboBox.getModel().getSelectedItem().toString();
        gameClient.CreateGame(current);
        navigator.navigateToGame(new StartGameDto(viewModel.getSelectedMap()));
    }//GEN-LAST:event_CreateGameButtonActionPerformed

    private void JoinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinGameActionPerformed
        try {
            StartGameDto startGameDto = gameClient.JoinGame();
            navigator.navigateToGame(startGameDto);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Потеряна связь с сервером.");
            navigator.navigateToStart();
        }
    }//GEN-LAST:event_JoinGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateGameButton;
    private javax.swing.JButton JoinGame;
    private javax.swing.JComboBox MapComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
